#!/bin/bash

set -e
shopt dotglob

container="$1"
section="$2"
hook_type="$3"

if [[ -z "$container" || "$section" != lxc || "$hook_type" != clone ]]; then
    echo "Error: Invalid parameters" >&2
    exit 1
fi

if ! [[ -d "$LXC_ROOTFS_MOUNT" ]]; then
    echo "Error: rootfs is not a directory" >&2
    exit 1
fi

UIDMAPSHIFT_INSTALL_PATH="/usr/local/bin/uidmapshift"

check_uidmapshift()
{
    if ! UIDMAPSHIFT=$(which uidmapshift); then
        wget https://bazaar.launchpad.net/~serge-hallyn/+junk/nsexec/download/head:/uidmapshift.c-20121030152620-2zy9rkac9y6htoia-8/uidmapshift.c
gcc -o uidmapshift uidmapshift.c
sudo mv uidmapshift /usr/bin/uidmapshift
rm -f uidmapshift.c
fi
 

}

# Container had user namespace mappings. Create new ones then execute the script
# again

if ! (( LXC_CLONE_IN_USERNS )) && grep -q '^lxc.id_map[[:blank:]*=' "$LXC_CONFIG_FILE"; then
    check_uidmapshift

        lx
    export LXC_CLONE_IN_USERNS=1






echo "Setting up hostname"

echo "$container" > "${LXC_ROOTFS_MOUNT}/etc/hostname"
sed -i -E "s/ ${LXC_SRC_NAME}\\([[:blank:]]|\$\\)/ ${container}\\1/" \
 "${LXC_ROOTFS_MOUNT}/etc/hosts"

###

echo "Cleaning shell history"

rm -f ${LXC_ROOTFS_MOUNT}/root/.*history

###

echo "Cleaning up DHCP leases"

rm -f ${LXC_ROOTFS_MOUNT}/var/lib/dhclient/*

###

echo "Cleaning temporary dirs"

rm -rf ${LXC_ROOTFS_MOUNT}/{tmp,var/tmp}/*

###

echo "Cleaning udev persistent net rules"

rm -f ${LXC_ROOTFS_MOUNT}/etc/udev/*-persistent-net.rules

###

echo "Cleaning up SSH known hosts"

rm -f ${LXC_ROOTFS_MOUNT}/root/.ssh/known_hosts

echo "Recreating SSH host keys"

rm -f ${LXC_ROOTFS_MOUNT}/etc/ssh/*_host_*

ssh-keygen -f "${LXC_ROOTFS_MOUNT}/etc/ssh/ssh_host_rsa_key" -N '' -t rsa
ssh-keygen -f "${LXC_ROOTFS_MOUNT}/etc/ssh/ssh_host_dsa_key" -N '' -t dsa
ssh-keygen -f "${LXC_ROOTFS_MOUNT}/etc/ssh/ssh_host_ecdsa_key" -N '' -t ecdsa \
 -b 521

###