#!/bin/bash

set -e
shopt dotglob

src_dir=$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")
. "${src_dir}/lxc-hook-utils"

if ! lxc_hook_check_params "$@" || [[ "$lxc_hook_type" != clone|sysprep ]]; then
    exit 1
fi

# Run in the user namespace if needed

if ! lxc_userns_maybe_reexec "$LXC_CONFIG_FILE" -- "$0" "$@"; then
    echo "Error: failed checking userns mapping for execution" >&2
    exit 1
fi

echo "Setting up hostname"

echo "$container" > "${LXC_ROOTFS_MOUNT}/etc/hostname"
sed -i -E "s/ ${LXC_SRC_NAME}\\([[:blank:]]|\$\\)/ ${container}\\1/" \
 "${LXC_ROOTFS_MOUNT}/etc/hosts"

###

echo "Cleaning shell history"

rm -f ${LXC_ROOTFS_MOUNT}/root/.*history

###

echo "Cleaning up DHCP leases"

rm -f ${LXC_ROOTFS_MOUNT}/var/lib/dhclient/*

###

echo "Cleaning temporary dirs"

rm -rf ${LXC_ROOTFS_MOUNT}/{tmp,var/tmp}/*

###

echo "Cleaning udev persistent net rules"

rm -f ${LXC_ROOTFS_MOUNT}/etc/udev/*-persistent-net.rules

###

echo "Cleaning up SSH known hosts"

rm -f "${LXC_ROOTFS_MOUNT}/root/.ssh/known_hosts"

echo "Recreating SSH host keys"

rm -f ${LXC_ROOTFS_MOUNT}/etc/ssh/*_host_*

ssh-keygen -f "${LXC_ROOTFS_MOUNT}/etc/ssh/ssh_host_rsa_key" -N '' -t rsa
ssh-keygen -f "${LXC_ROOTFS_MOUNT}/etc/ssh/ssh_host_dsa_key" -N '' -t dsa
ssh-keygen -f "${LXC_ROOTFS_MOUNT}/etc/ssh/ssh_host_ecdsa_key" -N '' -t ecdsa \
 -b 521

###