#!/bin/bash

set -e

###

src_dir=$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")
. "${src_dir}/../lxc-utils.bash"

script_name=$(basename "${BASH_SOURCE[0]}")

###

inf() { echo "Info:" "$@" >&2; }

###

if ! lxc_hook_check_params "$@" || [[ "$lxc_hook_type" != clone ]]; then
    exit 1
fi

echo "rootfs: $LXC_ROOTFS_MOUNT"
exit 1

lxc_cfg_userns_get "$LXC_CONFIG_FILE" uid_map gid_map

if [[ -z "$uid_map" && -z "$gid_map" ]]; then
    inf "No existing user or group mappings found"
else
    if [[ -n "$new_uid_map" ]]; then
        inf "Previous user mapping: ${uid_map}"
    fi

    if [[ -n "$new_gid_map" ]]; then
        inf "Previous group mapping: ${gid_map}"
    fi
fi

lxc_cfg_userns_set "$LXC_CONFIG_FILE" "new" "new"
lxc_cfg_userns_get "$LXC_CONFIG_FILE" new_uid_map new_gid_map

if [[ -n "$new_uid_map" ]]; then
    inf "New user mapping: ${new_uid_map}"
fi

if [[ -n "$new_gid_map" ]]; then
    inf "New group mapping: ${new_gid_map}"
fi

lxc_fs_userns_apply "$LXC_CONFIG_FILE" "$LXC_ROOTFS_MOUNT"